name: idp_new
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
    - cobra==0.29.0
    - arviz==0.13.0
    - scipy==1.9.3
    - pandas 
    - cloudpickle
    - numpy==1.24
    - pymc==4.3.0
    - pytensor
    - seaborn==0.12.1
    - tqdm
    - ipython
    - ipykernel